[homelab]
# Remplace par l'IP ou hostname de ton serveur homelab
homelab-server ansible_host=192.168.1.100 ansible_user=ubuntu

[homelab:vars]
ansible_ssh_private_key_file=~/.ssh/id_rsa
ansible_python_interpreter=/usr/bin/python3
